name = "AML"
uuid = "6b84a0a3-a11a-41fa-a417-e600528de108"
authors = ["Amin Yahyaabadi"]
version = "0.2.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[compat]
julia = "1"
EzXML = "0.9.4" # should be updated regularly

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
